[workspace]
authors = ["saint0x <saint.0x.saint@gmail.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "aria-mojo-build"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
mojo = ">=25.6.0.dev2025080620,<26"
